const mockLoans = [
  {
    id: 143871,
    url: 'https://app.zonky.cz/loan/143871',
    name: 'Výhodná koupě nemovitostí',
    story: 'Vážení investoři. Moje jméno je Lukáš a jsem vedoucí kompostárny. Jsem jeden z investorů na zonky, kde měsíčně investuji. Pravidelně spořím také přes investiční fondy. Jako bývalý finanční poradce si ve svém věku 26 let plně uvědomuji důležitost spoření. Rád hrají nohejbal, lyžuji a zajímám se o investování. Nějaké peníze mám již naspořené. Peníze od Vás, investorů, chci využít na koupi dvou bytů, které budu dále pronajímat. Návratnost je do 7 let. Měsíční splátka mě neomezí v mém spoření ani investování zde na zonky. Děkuji všem, kteří mě podpoří a zainvestují. ',
    purpose: '7',
    photos: [
      {
        name: 'othe-default.cbec3a78.png',
        url: '/loans/143871/photos/15975',
      },
    ],
    userId: 177397,
    nickName: 'Klukyn',
    termInMonths: 84,
    interestRate: 0.039900,
    rating: 'AAAAA',
    topped: null,
    amount: 500000.00,
    remainingInvestment: 499600.00,
    investmentRate: 8.0E-4,
    covered: false,
    datePublished: '2017-10-09T19:39:36.088+02:00',
    published: true,
    deadline: '2017-10-11T19:23:35.713+02:00',
    myOtherInvestments: null,
    investmentsCount: 1,
    questionsCount: 1,
    region: '6',
    mainIncomeType: 'EMPLOYMENT',
  },
  {
    id: 144860,
    url: 'https://app.zonky.cz/loan/144860',
    name: 'Vybavujeme dům',
    story: 'Milí investoři, po 6 letech bydlení v nájmu jsme se rozhodli postavit dům. Dům už stojí a teď ho zbývá vybavit. Rád bych si na část vybavení půjčil od Vás. Zbytek financujeme z vlastních zdrojů a tuto půjčku hodlám předčasně splatit. Děkuji za Vaši důvěru a přeji Vám všem krásný den!',
    purpose: '7',
    photos: [
      {
        name: 'shutterstock_309783218.08d6c2b3.jpg',
        url: '/loans/144860/photos/15925',
      },
    ],
    userId: 178451,
    nickName: 'JirkaStavitel',
    termInMonths: 78,
    interestRate: 0.039900,
    rating: 'AAAAA',
    topped: null,
    amount: 280000.00,
    remainingInvestment: 0.00,
    investmentRate: 1.0,
    covered: true,
    datePublished: '2017-10-08T19:57:27.895+02:00',
    published: true,
    deadline: '2017-10-10T19:47:51.287+02:00',
    myOtherInvestments: null,
    investmentsCount: 27,
    questionsCount: 0,
    region: '11',
    mainIncomeType: 'SELF_EMPLOYMENT',
  },
  {
    id: 143474,
    url: 'https://app.zonky.cz/loan/143474',
    name: 'Relax',
    story: 'Dobrý den. Poptávám investory, kteří by zainvestovali mou koupi nemovitosti pro účely rodinné rekreace a relaxu v podhůří Beskyd. Do nedávna jsem sdílel chatu rodičů se svou sestrou. Avšak po otcově smrti, se kterým jsem chatu udržoval, jsem se dozvěděl, že jediným majitelem chaty je právě má sestra, která rodičům nikdy s ničím nepomohla. Vznikly tudíž  neshody, které nakonec vyústily v mé rozhodnutí si pořídit chatu vlastní, na které budu moci realizovat své kutilské plány, které jsem s otcem již nestihl dokončit.  Byl to právě on, kdo mne naučil lásky k řemeslu,  přírodě a k horám vůbec. Proto bych i já velmi rád pokračoval ve šlépějích svého otce a předával veškerá moudra, zkušenosti a rady jak žít v souladu s přírodou svým vnoučatům, která jednou v budoucnu přijdou.  Předem děkuji všem potencionální investorům, které můj investiční záměr oslovil. ',
    purpose: '9',
    photos: [
      {
        name: 'othe-default.cbec3a78.png',
        url: '/loans/143474/photos/15922',
      },
    ],
    userId: 176973,
    nickName: 'zonky176973',
    termInMonths: 84,
    interestRate: 0.039900,
    rating: 'AAAAA',
    topped: null,
    amount: 500000.00,
    remainingInvestment: 0.00,
    investmentRate: 1.0,
    covered: true,
    datePublished: '2017-10-08T12:13:14.203+02:00',
    published: true,
    deadline: '2017-10-10T12:04:04.580+02:00',
    myOtherInvestments: null,
    investmentsCount: 12,
    questionsCount: 0,
    region: '13',
    mainIncomeType: 'EMPLOYMENT',
  },
  {
    id: 145795,
    url: 'https://app.zonky.cz/loan/145795',
    name: 'Dokončení domu',
    story: 'Dobrý den investoři,\npoptávám 320 000 Kč - ne na dokončení domu, ten je již komplet hotový, ale vrácení půjčky otci. Dům stál cca 4,3M Kč, pozemek jsme měli vlastní, hypo 2,8M Kč. Cca 900 000 Kč jsme dali z úspor (plus veškeré vydělané peníze za poslední rok), ale na dokončení fasády a venkovní dlažby jsem si půjčil od otce. Slíbil jsem vrátit do konce roku- bohužel již teď vím, že do konce roku tolik peněz navíc nevydělám a nechci se opozdit se splacením. Proto žádám o půjčku zde na Zonky, s úmyslem splatit celou jistinu příští rok (pokud vše půjde podle plánu).\nŽádný osobní příběh bohužel nemám :)\n\nNaše finance: \nPříjmy dostatečné\nNáklady: 10k měsíčně hypo, 5k energie, 2 malé děti a manželka\nDěkuji za investice.\n\nDavid\n',
    purpose: '7',
    photos: [
      {
        name: 'dvůr.jpg',
        url: '/loans/145795/photos/15895',
      },
    ],
    userId: 179450,
    nickName: 'David31',
    termInMonths: 41,
    interestRate: 0.039900,
    rating: 'AAAAA',
    topped: null,
    amount: 320000.00,
    remainingInvestment: 0.00,
    investmentRate: 1.0,
    covered: true,
    datePublished: '2017-10-06T17:51:05.250+02:00',
    published: true,
    deadline: '2017-10-08T17:40:27.052+02:00',
    myOtherInvestments: null,
    investmentsCount: 31,
    questionsCount: 1,
    region: '2',
    mainIncomeType: 'SELF_EMPLOYMENT',
  },
  {
    id: 139923,
    url: 'https://app.zonky.cz/loan/139923',
    name: 'Refinancování půjčky',
    story: 'Vážení investoři,\njsem spolumajitelem rodinného domu. Při jarním tání jsme přišli na to, že nám do domu zatéká. Jelikož jsme neměli pohromadě takovou investici museli jsme si na novou střechu půjčit. Jelikož peněz není nikdy dost a zjistil jsem, že Zonky mi může poskytnout lepší nabídku, rozhodl jsem se mojí stávající půjčku refinancovat. Doufám, že mi pomůžete a rozhodnete se investovat do mého refinancování. Předem Vám všem děkuji.\nMiloš',
    purpose: '6',
    photos: [
      {
        name: '6',
        url: '/loans/139923/photos/15880',
      },
    ],
    userId: 173154,
    nickName: 'zonky173154',
    termInMonths: 43,
    interestRate: 0.039900,
    rating: 'AAAAA',
    topped: null,
    amount: 215000.00,
    remainingInvestment: 0.00,
    investmentRate: 1.0,
    covered: true,
    datePublished: '2017-10-06T16:12:57.301+02:00',
    published: true,
    deadline: '2017-10-08T16:02:10.292+02:00',
    myOtherInvestments: null,
    investmentsCount: 24,
    questionsCount: 1,
    region: '6',
    mainIncomeType: 'EMPLOYMENT',
  },
];

export default mockLoans;
